version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    image: food4g-api:latest
    command: >
      sh -c "npm uninstall bcrypt && npm install bcrypt && npm start"